### ISSUE TITLE
tag / release new version

### ISSUE THREAD

**Issue by BarthV** [redguide/locales#6]
at least inside github only at the moment

**Comment by guilhem** [comment]
:+1:

**Comment by Sliim** [comment]
Ok for me, maybe we can start with 0.4.0?
Latest release was 0.3.1 in phbergsmann's repo

**Comment by BarthV** [comment]
sounds good to me.

**Comment by Sliim** [comment]
I bumped version 0.4.0 inside a PR, I'm not sure for the changelog..
Also I pushed old tags, from 0.1.1 to 0.3.1.

**Comment by Sliim** [comment]
Pushed tag 0.4.0 :)
